# -*- coding: utf-8 -*-
"""webscrapping_demo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vh7Y70CcJk9STGLjGfh9wj4pnxXuQ0Xk
"""

import pandas as pd
import requests
from bs4 import BeautifulSoup

headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}

webpage=requests.get('https://www.ambitionbox.com/list-of-companies?campaign=desktop_nav&page=1',headers=headers).text

soup=BeautifulSoup(webpage,'lxml')

company=soup.find_all('div',class_='companyCardWrapper')

final=pd.DataFrame()
for j in range(1,200):
  url='https://www.ambitionbox.com/list-of-companies?campaign=desktop_nav&page={}'.format(j)
  headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
  webpage=requests.get(url,headers=headers).text
  soup=BeautifulSoup(webpage,'lxml')
  company=soup.find_all('div',class_='companyCardWrapper')

  name=[]
  reviews=[]
  employee=[]
  rating=[]
  ctype=[]
  highlyratedfor=[]
  years=[]
  for i in company:
    name.append(i.find('h2').text.strip())
    rating.append(i.find('span',class_='companyCardWrapper__companyRatingValue').text.strip())
    ctype.append(i.find('span',class_='companyCardWrapper__interLinking').text.split('|')[0].strip())
    try:
      employee.append(i.find('span',class_='companyCardWrapper__interLinking').text.split('|')[1].strip())
    except:
      employee.append('null')
    reviews.append(i.find('span',class_='companyCardWrapper__ActionCount').text.strip())
    try:
      years.append(i.find('span',class_='companyCardWrapper__interLinking').text.split('|')[3].strip())
    except:
          years.append('null')

    try:
      highlyratedfor.append(i.find('span',class_='companyCardWrapper__ratingValues').text)
    except:
      highlyratedfor.append('null')


  d={'name':name,'years':years,'reviews':reviews,'employee':employee,'rating':rating,'type':ctype,'highly_rated_for':highlyratedfor}
  df=pd.DataFrame(d)
  final=final.append(df,ignore_index=True)

final

final.to_csv('Companies_list.csv', index=False)